name: Test PR

on:
  pull_request_target:
  workflow_call:
  workflow_dispatch:

jobs:
  test-protocol-with-repo-variables:
    if: ${{ vars.USE_CUSTOM_VARIABLES == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
      - name: Test evaluation
        run: |
            chmod -R +x .
            export PROTOCOL=${{vars.PROTOCOL}} && ./tests/setup_and_run.sh
  test-protocol-with-env-variables:
    if: ${{ vars.USE_CUSTOM_VARIABLES != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get Test folder
        uses: actions/checkout@v4
        with:
          path: environment
      - name: Prepare environment
        run: |
          chmod -R +x .
          rm -r tests/
          cp -r environment/tests/ .
          ./env.sh
      - name: Test evaluation
        run: |
          ./tests/setup_and_run.sh
        env: 
          PROTOCOL: ${{ env.PROTOCOL }}
